"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

files:
  - source: /mods-dll/thebasics/assets/thebasics/lang/en.json
    translation: /mods-dll/thebasics/assets/thebasics/lang/%two_letters_code%.json
