"""Reusable Vintage Story model-rendering library."""

from .cli import build_parser, main
from .core import (
    FACE_INDICES,
    FALLBACK_COLORS,
    RENDER_MODES,
    VIEWS,
    CoplanarOverlap,
    Face,
    Vec2,
    Vec3,
    add,
    convex_intersection_area,
    cross,
    cross_2d,
    cuboid,
    dot,
    face_normal,
    find_coplanar_overlaps,
    intersect_lines,
    mul,
    normalize,
    projected_face,
    rotate,
    signed_polygon_area,
    sub,
)
from .flywheel import add_annulus, add_rotated_cuboid, constants, load_flywheel
from .rendering import (
    average_color,
    fixed_animation_projections,
    projection,
    projection_for_view,
    rasterize_edge,
    rasterize_triangle,
    render,
    resolve_texture,
    rotate_view_around_y,
    screen_point,
)
from .shapes import face_uvs, lerp, load_shape, sample_animation_pose
from .video import (
    animation_sample_positions,
    contact_sheet,
    render_animation,
    render_turntable,
    sha256,
    turntable_frame_count,
)

__all__ = [
    "FACE_INDICES",
    "FALLBACK_COLORS",
    "RENDER_MODES",
    "VIEWS",
    "CoplanarOverlap",
    "Face",
    "Vec2",
    "Vec3",
    "add",
    "add_annulus",
    "add_rotated_cuboid",
    "animation_sample_positions",
    "average_color",
    "build_parser",
    "constants",
    "contact_sheet",
    "convex_intersection_area",
    "cross",
    "cross_2d",
    "cuboid",
    "dot",
    "face_normal",
    "face_uvs",
    "find_coplanar_overlaps",
    "fixed_animation_projections",
    "intersect_lines",
    "lerp",
    "load_flywheel",
    "load_shape",
    "main",
    "mul",
    "normalize",
    "projected_face",
    "projection",
    "projection_for_view",
    "rasterize_edge",
    "rasterize_triangle",
    "render",
    "render_animation",
    "render_turntable",
    "resolve_texture",
    "rotate",
    "rotate_view_around_y",
    "sample_animation_pose",
    "screen_point",
    "sha256",
    "signed_polygon_area",
    "sub",
    "turntable_frame_count",
]
